[package]
publish=false
name = "ydb-example-urlshortener"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket="0.5.0-rc.1"
ydb={path="../sdk"}