[package]
publish=false
name = "ydb-grpc"
version="0.0.0"
authors = ["rekby <timofey.koolin@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
description = "Crate contain helpers for generate grpc imports in ydb-grpc crate."
repository = "https://github.com/ydb-platform/ydb-rs-sdk/tree/master/ydb-grpc-helpers"

[dependencies]
prost = "0.9.0"
prost-types = "0.9.0"

tonic = {version = "0.6", features=["tls", "tls-roots", "tls-webpki-roots"]}

[build-dependencies]
ydb-grpc-helpers = {version="0.0.2", path="../ydb-grpc-helpers"}
prost-build = "0.9.0"
tonic-build = "0.6"
walkdir = "2"

[features]
regenerate-sources = []
