[package]
publish=false
name = "rs-ydb-sdk"
version = "0.1.0"
authors = ["rekby <timofey.koolin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prost = "0.8"

[build-dependencies]
tonic-build = "0.5"
