[package]
publish=false
name = "sdk"
version = "0.0.0"
authors = ["rekby <timofey.koolin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dyn-clone = "1"
http = "0.2"
prost = "0.8"
tokio = "1"
tonic = "0.5"
tower = "0.4"
ydb-protobuf = {path="../ydb-protobuf"}