name: Publish rust crate to crates.io
on:
  workflow_dispatch:
    inputs:
      crate:
        description: Publish crate to crates.io
        required: true
        type: choice
        default: ydb
        options:
          - ydb
          - ydb-grpc
          - ydb-grpc-helpers
      version-part:
        description: "Part of version to changes major.minor.patch (can select patch or minor only)"
        required: true
        type: choice
        default: patch
        options:
          - patch
          - minor

permissions:
  contents: write

jobs:
  publishCrate:
    runs-on: ubuntu-latest
    env:
      GIT_EMAIL: ${{ github.actor }}@users.noreply.github.com
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      TAG_VERSION: ${{ github.event.inputs.crate }}-${{ github.event.inputs.version }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: ./.github/scripts/version-up.sh "${{ github.event.inputs.crate }}" "${{ github.event.inputs.version-part }}" "$GIT_EMAIL"
