name: YDB tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '18 4 * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  tests:
    strategy:
      matrix:
        rust_version: [ "1.56.0", "1.62.1" ]

    runs-on: ubuntu-20.04

    steps:
    - name: Install fixed rust version
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: ${{ matrix.rust_version }}
        components: clippy

    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Rust version
      id: rust_version_step
      run: echo "::set-output name=version::$(rustc --version | cut -d ' ' -f 2)"

    - name: Cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-${{ steps.rust_version_step.outputs.version }}-cargo-${{ hashFiles('**/Cargo.lock') }}-1
        path: |
          ~/.cargo/bin/
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/.package-cache
          ~/.cargo/registry/
          ~/.cargo/git/db/
          target/

    - name: Linter
      if: matrix.rust_version != '1.56.0'
      run: |
        cargo clippy --workspace --all-targets --all-features -- -D warnings

    - name: Build
      run: cargo build --verbose --workspace --all-targets

    - name: Wait database available
      run: bash ./.github/scripts/start-ydb-container.sh

    - name: Run tests
      env:
        YDB_CONNECTION_STRING: grpc://localhost:2136?database=/local
      run: cargo test --verbose --workspace -- --include-ignored --nocapture
