name: Unit tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Install fixed rust version
      uses: ATiltedTree/setup-rust@v1
      with:
        rust-version: 1.56.0

    - name: Cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-
        path: |
          ~/.cargo/bin/
          ~/.cargo/.crates.toml
          ~/.cargo/.crates2.json
          ~/.cargo/.package-cache
          ~/.cargo/registry/
          ~/.cargo/git/db/
          target/

    - name: Rust check versions
      run: |
        cargo version
        rustc --version

    - name: Build
      run: cargo build --verbose --workspace

    - name: Run tests
      run: cargo test --verbose --workspace
